import { text, rich, group } from "./_helpers";

/**
 * Home page field schema. Groups follow the page top-to-bottom so an editor
 * recognises where each field lands. Keys map 1:1 to the `home.*` i18n group.
 */
export default {
  groups: [
    group("Hero", [
      text("home.hero.subtitle", "Eyebrow"),
      rich("home.hero.title", "Headline (line breaks allowed)"),
      text("home.hero.location", "Location line"),
      text("home.hero.ctaVisit", "Button — Plan a visit"),
      text("home.hero.ctaMass", "Button — Mass & Confession"),
      text("home.hero.ctaBecoming", "Button — Becoming Catholic"),
      text("home.hero.espanolPrompt", "Spanish-language prompt button"),
    ]),
    group("Today / Essentials strip", [
      text("home.essentials.todayGroup", "Group label — Today"),
      text("home.essentials.findUs", "Group label — Find us"),
      text("home.essentials.today", "Masses label"),
      text("home.essentials.noMassToday", "No Mass today message"),
      text("home.essentials.confession", "Confession label"),
      text("home.essentials.noConfessionToday", "No Confession today message"),
      text("home.essentials.directions", "Address label"),
      text("home.essentials.directionsDesc", "Address value"),
      text("home.essentials.bulletin", "Bulletin label"),
      text("home.essentials.bulletinDesc", "Bulletin description"),
      text("home.essentials.contact", "Call-the-office label"),
      text("home.essentials.reviewed", "Times-verified note"),
    ]),
    group("Welcome", [
      text("home.welcome.sub", "Eyebrow"),
      text("home.welcome.title", "Heading"),
      rich("home.welcome.p1", "Paragraph 1"),
      rich("home.welcome.p2", "Paragraph 2"),
      text("home.welcome.cta", "Button"),
    ]),
    group("Mass & Confession call-to-action", [
      text("home.massCta.sub", "Eyebrow"),
      text("home.massCta.title", "Heading"),
      rich("home.massCta.desc", "Description"),
      text("home.massCta.cta", "Button"),
      text("home.massCta.sundayMass", "Weekend Mass label"),
      text("home.massCta.satVigil", "Saturday vigil label"),
      text("home.massCta.sun", "Sunday label"),
      text("home.massCta.sunEspanol", "Sunday (Español) label"),
    ]),
    group("Priests & Staff", [
      text("home.priests.sub", "Eyebrow"),
      text("home.priests.title", "Heading"),
      text("home.priests.quote", "Quote"),
      text("home.priests.quoteSrc", "Quote attribution"),
      rich("home.priests.desc", "Description"),
      text("home.priests.cta", "Button — meet the team"),
      text("home.priests.province", "Button — our province"),
    ]),
    group("Get Involved", [
      text("home.involved.sub", "Eyebrow"),
      text("home.involved.title", "Heading"),
      rich("home.involved.desc", "Description"),
      text("home.involved.ctaRegister", "Button — register"),
      text("home.involved.ctaBulletin", "Button — bulletins"),
    ]),
    group("News & Announcements", [
      text("home.announcements.sub", "Eyebrow"),
      text("home.announcements.title", "Heading"),
      text("home.announcements.ctaBulletin", "Button — full bulletin"),
      text("home.announcements.upcoming", "Upcoming label"),
    ]),
    group("Next-Mass countdown", [
      text("home.nextMass.label", "Label"),
      text("home.nextMass.days", "Days unit"),
      text("home.nextMass.hours", "Hours unit"),
      text("home.nextMass.min", "Minutes unit"),
      text("home.nextMass.sec", "Seconds unit"),
      text("home.nextMass.in", "Joining word — in"),
    ]),
    group("Our Mission — Word, Sacrament & Service", [
      text("home.pillars.sub", "Eyebrow"),
      text("home.pillars.title", "Heading"),
      text("home.pillars.word.title", "Pillar 1 — title"),
      rich("home.pillars.word.desc", "Pillar 1 — description"),
      text("home.pillars.sacrament.title", "Pillar 2 — title"),
      rich("home.pillars.sacrament.desc", "Pillar 2 — description"),
      text("home.pillars.service.title", "Pillar 3 — title"),
      rich("home.pillars.service.desc", "Pillar 3 — description"),
    ]),
    group("Liturgical season labels", [
      text("home.liturgical.advent", "Advent"),
      text("home.liturgical.christmas", "Christmas"),
      text("home.liturgical.lent", "Lent"),
      text("home.liturgical.triduum", "Triduum"),
      text("home.liturgical.easter", "Easter"),
      text("home.liturgical.ordinary", "Ordinary Time"),
    ]),
    group("Vatican News widget", [
      text("home.vatican.sub", "Eyebrow"),
      text("home.vatican.title", "Heading"),
      text("home.vatican.load", "Load button"),
      text("home.vatican.loading", "Loading message"),
      rich("home.vatican.privacy", "Privacy note"),
    ]),
    group("Faith Formation teaser", [
      text("home.formation.sub", "Eyebrow"),
      text("home.formation.title", "Heading"),
      rich("home.formation.desc", "Description"),
    ]),
    group("Contact cards", [
      text("home.cards.visitTitle", "Visit card title"),
      text("home.cards.callTitle", "Call card title"),
      text("home.cards.hoursTitle", "Hours card title"),
      text("home.cards.hoursDays", "Hours — days"),
      text("home.cards.hoursTime", "Hours — time"),
      text("home.cards.emailTitle", "Email card title"),
    ]),
    group("Events", [text("home.events.cta", "Button — view all events")]),
  ],
};
